Importing libraries

In [0]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest, f_classif

Importing files

In [67]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [68]:
cd 'gdrive/My Drive/Colab Notebooks'

[Errno 2] No such file or directory: 'gdrive/My Drive/Colab Notebooks'
/content/gdrive/My Drive/Colab Notebooks


Reading file

In [0]:
creditcard = pd.read_csv("creditcard.csv")

In [70]:
creditcard.head()

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [0]:
array = creditcard.values

Separating the data from the target

In [72]:
X = array[:, 0:30]
Y = array[:, 30]
print(X.shape)

(284807, 30)


Choosing the best features

In [73]:
X_new = SelectKBest(f_classif, k=15).fit_transform(X, Y)
print(X_new.shape)

(284807, 15)


In [74]:
df = pd.DataFrame(X_new)
df.head()

0         1         2   ...        12        13        14
0 -1.359807 -0.072781  2.536347  ... -0.470401  0.207971  0.025791
1  1.191857  0.266151  0.166480  ...  0.463917 -0.114805 -0.183361
2 -1.358354 -1.340163  1.773209  ... -2.890083  1.109969 -0.121359
3 -0.966272 -0.185226  1.792993  ... -1.059647 -0.684093  1.965775
4 -1.158233  0.877737  1.548718  ... -0.451449 -0.237033 -0.038195

[5 rows x 15 columns]

Separating data so that we can analyse it in a confusion matrix

In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df, Y)

Importing the model

In [0]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5)

Fitting the model


In [77]:
model.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

Making the prediction

In [78]:
prediction = model.predict(x_test)
print(prediction)

[0. 0. 0. ... 0. 0. 0.]


Analysing the score

In [79]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, df, Y, cv = 5)
print(scores)

[0.99899933 0.99956111 0.9989642  0.99947332 0.99942066]


Getting the mean of scored values

In [84]:
mean = np.mean(scores)
print(mean)

0.9992837254948339


Making the confusion matrix: 71074 true negatives, 4 false negatives, 26 false positives, 98 true positives

In [82]:
from sklearn.metrics import confusion_matrix 
results = confusion_matrix(y_test, prediction)
print(results)

[[71074     4]
 [   26    98]]
